index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: base.html.twig

api_login_check:
    path: /api/v1/auth/login_check

gesdinet_jwt_refresh_token:
    path: /api/v1/auth/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }